<a href="https://colab.research.google.com/github/Manojkumar310897/numpy-stats-assignment-2/blob/main/Numpy_stats_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [107]:
a=np.arange(10)+1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


# Reshaping of vector and Creating 10X10 Matrix

In [104]:
a = np.arange(1,11)
b = np.arange(1,11)[:, np.newaxis]

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [106]:
c=a+b
print(c)
print(c.shape)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
(10, 10)


## **Creating Dataset**

In [82]:
import numpy.random as npr
data = np.exp ( npr.randn(50, 5))
data

array([[ 0.46724321,  0.99763831,  0.26120075,  4.77884074,  0.36922552],
       [ 0.51755398,  1.71950437,  0.34304825,  0.31542581,  0.14325094],
       [ 0.32509526,  4.38407296,  1.38613123,  0.23076017,  1.39066666],
       [ 0.73755869,  0.20252331,  0.79576573,  0.35934156,  0.44884293],
       [ 1.96629851,  0.70119037,  0.98898643,  5.7763258 ,  2.39635361],
       [ 0.30265759,  1.41208407,  0.71822995,  0.90756068,  0.44200602],
       [ 0.49995205,  1.76357921,  1.74361159,  0.9119278 ,  0.45779867],
       [ 1.00215806,  0.9713018 ,  1.18917634,  1.13607379,  0.3847126 ],
       [ 0.69605445,  0.23901037,  0.48441389,  1.64833966,  0.92843486],
       [ 0.33747446,  1.53092046,  0.21522926,  1.29948205,  2.98349212],
       [ 3.37076825,  0.96412737,  0.42908836,  0.5444839 ,  0.98438416],
       [ 0.76562566,  0.13933238,  2.20193951,  0.50483124,  1.58059269],
       [ 0.71497509,  2.44423532,  1.70159787,  0.5719671 ,  0.52723216],
       [ 9.49777974,  1.18629506,  1.1

# **Mean and Standard Deviation**

In [83]:
dmean=data.mean(0)
dmean

array([1.9493103 , 1.74037468, 1.35817626, 1.4055519 , 1.25371842])

In [84]:
dstd=data.std(axis=0)
dstd

array([2.5113732 , 1.72348108, 1.50952062, 1.68932269, 1.51984596])

# Standardizing Data

#Using given formula Standardizing data

In [97]:
normalized = (data - dmean)/(dstd)
normalized

array([[-5.90142115e-01, -4.30951279e-01, -7.26704556e-01,
         1.99682918e+00, -5.81962197e-01],
       [-5.70108943e-01, -1.21093956e-02, -6.72483700e-01,
        -6.45303641e-01, -7.30644756e-01],
       [-6.46743799e-01,  1.53392939e+00,  1.85191043e-02,
        -6.95421742e-01,  9.01066625e-02],
       [-4.82505591e-01, -8.92293737e-01, -3.72575590e-01,
        -6.19307571e-01, -5.29577012e-01],
       [ 6.76451302e-03, -6.02956613e-01, -2.44574222e-01,
         2.58729367e+00,  7.51809871e-01],
       [-6.55678218e-01, -1.90481122e-01, -4.23940095e-01,
        -2.94787501e-01, -5.34075439e-01],
       [-5.77117830e-01,  1.34637554e-02,  2.55336242e-01,
        -2.92202373e-01, -5.23684483e-01],
       [-3.77145157e-01, -4.46232273e-01, -1.11956023e-01,
        -1.59518431e-01, -5.71772298e-01],
       [-4.99032103e-01, -8.71123177e-01, -5.78834344e-01,
         1.43718998e-01, -2.14024027e-01],
       [-6.41814542e-01, -1.21529747e-01, -7.57158923e-01,
        -6.27883866e-02

In [98]:
normalized.mean(0)

array([-1.31006317e-16, -1.84297022e-16, -5.32907052e-17,  1.67088565e-16,
       -6.88338275e-17])

In [99]:
normalized.std(0)

array([1., 1., 1., 1., 1.])

**Standardizing data by importing libraries**

In [85]:
from sklearn import preprocessing
import numpy as np
scaler = preprocessing.StandardScaler().fit(data)
scaler
X_scaled = scaler.transform(data)
X_scaled

array([[-5.90142115e-01, -4.30951279e-01, -7.26704556e-01,
         1.99682918e+00, -5.81962197e-01],
       [-5.70108943e-01, -1.21093956e-02, -6.72483700e-01,
        -6.45303641e-01, -7.30644756e-01],
       [-6.46743799e-01,  1.53392939e+00,  1.85191043e-02,
        -6.95421742e-01,  9.01066625e-02],
       [-4.82505591e-01, -8.92293737e-01, -3.72575590e-01,
        -6.19307571e-01, -5.29577012e-01],
       [ 6.76451302e-03, -6.02956613e-01, -2.44574222e-01,
         2.58729367e+00,  7.51809871e-01],
       [-6.55678218e-01, -1.90481122e-01, -4.23940095e-01,
        -2.94787501e-01, -5.34075439e-01],
       [-5.77117830e-01,  1.34637554e-02,  2.55336242e-01,
        -2.92202373e-01, -5.23684483e-01],
       [-3.77145157e-01, -4.46232273e-01, -1.11956023e-01,
        -1.59518431e-01, -5.71772298e-01],
       [-4.99032103e-01, -8.71123177e-01, -5.78834344e-01,
         1.43718998e-01, -2.14024027e-01],
       [-6.41814542e-01, -1.21529747e-01, -7.57158923e-01,
        -6.27883866e-02

In [86]:
X_scaled.mean(axis=0)

array([-1.31006317e-16, -1.84297022e-16, -5.32907052e-17,  1.67088565e-16,
       -6.88338275e-17])

In [87]:
X_scaled.std(axis=0)

array([1., 1., 1., 1., 1.])